### ISSUE TITLE
Should we have a INF status that identifies obj application is pending?

### ISSUE THREAD

**Issue by martinkennelly** [openshift/ingress-node-firewall#171]
While I was testing, I wanted to wait until application of INF is completed by the daemons, but I noticed there is no "Pending" state for `SyncStatus`.  Is this a gap?

**Comment by msherif1234** [comment]
It’s currently two state why not considering not synced as pending and wait till it go to sync successfully?

**Comment by martinkennelly** [comment]
but thats my point, we cannot detect its in pending state cause theres no state for this. It currently, if all is good, goes from "Synchronized" -> "Synchronized".

**Comment by martinkennelly** [comment]
Id like it to go from "Synchronized" -> "Pending" -> "Synchronized".

**Comment by martinkennelly** [comment]
Within our test code we could watch for these transition states.
