### ISSUE TITLE
recent failures when running E2E on KinD

### ISSUE THREAD

**Issue by msherif1234** [openshift/ingress-node-firewall#224]
**Describe the bug**
1- the new netcat images are large in size so it requires longer timeout setting to run
I used 
```golang
-       timeout           = time.Second * 40
+       timeout           = time.Second * 400
```
2- IPv6 test cases fails probably some env setting I tried to disable firewalld but that didn't help as I work around I used
```golang
-       isSingleStack     = false
+       isSingleStack     = true
```
**To Reproduce**
1. bring up kind cluster
2. deploy operator
3. `make test-e2e`

**Expected behavior**
We should be able to run both IPv4 and IPv6 test cases on KinD

**Comment by andreaskaris** [comment]
Suggestion: prepull and load the image on cluster creation, I'll create a PR for that

**Comment by martinkennelly** [comment]
I ran into this issue and disabled firewalld. v6 tests work for me.
Ill look for a smaller test images.

**Comment by martinkennelly** [comment]
@msherif1234 confirmed the workaround to get IPV6 tests working:
```sh
sudo systemctl stop firewalld
sudo systemctl stop docker
sudo systemctl start docker
# create your cluster
```

**Comment by martinkennelly** [comment]
/close
Fixed with image size reduction and doc update.
