### ISSUE TITLE
RFE: allow blocking the SSH port

### ISSUE THREAD

**Issue by freedge** [openshift/ingress-node-firewall#287]
**Describe the bug**
as explicitly documented, today it's not possible to restrict access to SSH port, we get
```The  "ingressnodefirewall" is invalid: spec.ingress[0][rules][1]: Forbidden: port is in conflict with access to SSH```

**Expected behavior**
The SSH port is one we want to restrict as well to particular cidrs

**Additional context**
ingress-node-firewall.v4.12.0-202301042354.2

**Comment by msherif1234** [comment]
@freedge We intentionally prevent rules to block `SSH` traffic to make sure users can retain node access in case of something went wrong and there is a need to debug or collect node logs. 
https://github.com/openshift/ingress-node-firewall/blob/master/pkg/failsaferules/failsaferules.go#L24

can u pls explain your use case and if u want to block SSH on the main interface or the secondary one ?

**Comment by freedge** [comment]
I understand the rationale behind the idea.

We want to restrict SSH on the main interface and the rest of the failsafe ports to a subset of CIDRs for security reasons, so really, for the same reason as for other ports.

Opened SSH ports (especially on the infrastructure and accessible from the workload) pop up in security audits, example of report we could get:

> SSH instances are available on infrastructure nodes from virtual instance.
> This allows an attacker to mount bruteforce attack and
> potentially cause denial of service on locking critical accounts. 

Connecting through SSH using the core user is also discouraged, it should be done from a bastion where a user authenticated with his user account first, so that this action can be audited.
In the past when deploying OpenShift on OpenStack, OpenShift was deployed in its own private network and accessible only through a bastion (OpenStack itself only restricts SSH traffic from the ctlplane network).
On baremetal I would wish to retain this feature to enforce some kind of segmentation.

This is not anything mandatory btw, it's just a nice to have that makes sense I think (and could be implemented by just trashing code!) but if it does not feel free to close the ticket.

**Comment by msherif1234** [comment]
> I understand the rationale behind the idea.
> 
> We want to restrict SSH on the main interface and the rest of the failsafe ports to a subset of CIDRs for security reasons, so really, for the same reason as for other ports.
> 
> Opened SSH ports (especially on the infrastructure and accessible from the workload) pop up in security audits, example of report we could get:
> 
> > SSH instances are available on infrastructure nodes from virtual instance.
> > This allows an attacker to mount bruteforce attack and
> > potentially cause denial of service on locking critical accounts.
> 
> Connecting through SSH using the core user is also discouraged, it should be done from a bastion where a user authenticated with their user account first, so that this action can be audited. In the past when deploying OpenShift on OpenStack, OpenShift was deployed in its own private network and accessible only through a bastion (OpenStack itself only restricts SSH traffic from the ctlplane network). On baremetal I would wish to retain this feature to enforce some kind of segmentation.
> 
> This is not anything mandatory btw, it's just a nice to have that makes sense I think (and could be implemented by just trashing code!) but if it does not feel free to close the ticket.

for that use case u can use zero trust rule `sourcCIDR: 0.0.0.0/0` then selectively open the ports of interest including access to api-server with risk of hossing ur cluster, so really need to be very sure about all the ports u need opened, will that help your use case ?

**Comment by freedge** [comment]
yes! this looks perfect for my needs.
I'll do some more tests (I am not yet 100% sure I can use this. We still have traffic routed from metallb reaching the node, and it could target port 22 and be valid, in that case I may need the ability to filter on destinationCIDR as well).
Thanks for your reply!

**Comment by grandeit** [comment]
> for that use case u can use zero trust rule `sourcCIDR: 0.0.0.0/0` with `deny` as the default action see https://github.com/openshift/ingress-node-firewall/blob/master/config/samples/ingressnodefirewall-demo-denyall.yaml, then selectively open the ports of interest including access to api-server with risk of hossing ur cluster, so really need to be very sure about all the ports u need opened, will that help your use case ?

What is the rational behind not allowing users to block the SSH port but allowing them to lock themselves out completely by allowing a drop all rule?

As @freedge described, it would be benefitial to allow blocking the SSH port on machines that have multiple NICs. In my case I would like to restrict SSH access to a second network interface. Therefore, it is necessary to block port 22/TCP on the main interface. If one could block SSH I would only need to create _one_ rule for the main interface without worrying about any other ports.
