### ISSUE TITLE
Make resources namespaced or not

### ISSUE THREAD

**Issue by andreaskaris** [openshift/ingress-node-firewall#54]
Currentlly, we have:

* IngrNodeFwConfig -> namespaced
* IngressNodeFirewall -> cluster scope
* IngressNodeFirewallNodeState -> namespaced

I think that IngressNodeFirewallNodeState should be namespaced as it's read by the daemonset pods and I prefer using rolebindings to give access than clusterolebindings. For IngrNodeFwConfig and IngressNodeFirewall, I'm indifferent, but they should either both be namespaced or both be at cluster scope.

**Comment by msherif1234** [comment]
IngrNodeFwConfig is deploying the ds which is namedspace that is why its namespaced while the rules is cluster wide so not sure why u want to treat them the same ?

**Comment by msherif1234** [comment]
I think we are proceeding with the current objects so  iwill close this issue and we can reopen if needed
