### ISSUE TITLE
Use or extend to support rules for API IP served via metallb on baremetal

### ISSUE THREAD

**Issue by callum-stakater** [openshift/ingress-node-firewall#548]
We have openshift running on baremetal as a service where the nodes have public ips, and the API and apps are public IPs served via metallb 

Ingress-node-firewall appears ideal for blocking SSH etc to the public node IPs but ideally we need to restrict access to the API and apps virtual IPs on the nodes and it appears this is not possible due to the way it uses node selectors to get the IPs? 

In our use case if we could say instead an entire subnet instead of per node IP it would also work

**Comment by msherif1234** [comment]
Hi @callum-stakater thanks for opening this issue, I would like to get more details about your use case so I assume u are referring to nodeSelector in the rule object right ? which just a way to tell the scope of this rule on the cluster nodes but it has nothing to do with nodes IP

are u trying to control access for the API server on the main interface or the secondary interface ?

now for VIP which is dstIPs the node firewall doesn't really care about the dstIP it cares about from where this traffic originated and to what port so in theory u can use the svc port and protocol to construct ur firewall rule for ur apps VIP ?

**Comment by callum-stakater** [comment]
Yeah so currently the openshift API is publicly available as I believe a secondary interface on the master nodes (will need to check this to confirm) and ideally we want to restrict inbound access to a VPN exit node IP

For the node IPs it seemed obvious how to do this but we struggled when it came to restricting all inbound traffic (except intercluster communication and our VPN egress IP) to the openshift API IP which is just a virtual IP in the same range as the machine cidr

I'll take a closer look at what you wrote above and see if I can make sense of it, but from what I understand we could only restrict to the destination of the node IPs and not arbitrary IPs or a cidr range?

**Comment by callum-stakater** [comment]
Maybe I'm thinking about it wrong and if I understand what you are saying the destIPs are irrelevant we just need to filter the correct port/protocol (eg 6443 for API and 80/443 for apps)?

**Comment by msherif1234** [comment]
> Maybe I'm thinking about it wrong and if I understand what you are saying the destIPs are irrelevant we just need to filter the correct port/protocol (eg 6443 for API and 80/443 for apps)?

Yes

**Comment by msherif1234** [comment]
take a look at https://github.com/openshift/ingress-node-firewall/blob/master/docs/Statless%20Ingress%20Node%20Firewall.pdf for more details

**Comment by msherif1234** [comment]
if u wanted to block API server than you are right the wh will prevent u from doing that as that can have cluster wide impact so we tried to prevent user from locking up their own cluster
but if u are welling to take the risk maybe u can make use of the zero trust rule and open specificy the port of interest and deny the rest ?

**Comment by Andtalath** [comment]
Oh?
So the webhook will not block that?

Interesting.

**Comment by Andtalath** [comment]
Looks like you are right, it doesn't and it works.
Basically just whitelist the internal nets and any nets or IPs which are allowed to access.
Then just add a blocker for every other net, possibly with whitelists for stuff that needs it.
