### ISSUE TITLE
Rename IngrNodeFwConfig to IngressNodeFirewallConfig

### ISSUE THREAD

**Issue by andreaskaris** [openshift/ingress-node-firewall#55]
Rename IngrNodeFwConfig to IngressNodeFirewallConfig

**Comment by msherif1234** [comment]
@martinkennelly  @andreaskaris lets agree on domain name changes objects names and will do it all at once 
this is a manual process so better we do it once, also do i need to wait for u @andreaskaris so we won't collide or you are ok doing it now ?
