### ISSUE TITLE
Add API method to list all attached XDP interfaces

### ISSUE THREAD

**Issue by andreaskaris** [openshift/ingress-node-firewall#98]
Add API method to list all attached XDP interfaces; it's possible that a daemon goes down, the resource is updated, and *then* the daemon comes back up but it has no way of knowing which interfaces are attached. When a daemon comes up it must compare the current resource state to the currently attached interfaces.

We must cover the following corner case:

i) process up, attaches watch
===
spec:
  interfaces: A,B
===
applied on A,B

ii) process down, no watch

iii) spec updated:
~~~
spec:
  interfaces: A
~~~

iv) processs up, attaches watch
applied on A

===================================
Compare that to what happens when all goes well:

i) process up, attaches watch
===
spec:
  interfaces: A,B
===
applied on A,B

ii) spec updated:
~~~
spec:
  interfaces: A
~~~

iii) watch sees change in spec, process gets old and new

iv) processs up
applied on A   (and b can be deleted)

**Comment by msherif1234** [comment]
it seems we can use netlink to get list of interfaces https://pkg.go.dev/github.com/vishvananda/netlink#LinkXdp I will look into this
